### ISSUE TITLE
[Bug] App shows the file list unexpectedly

### ISSUE THREAD

**Issue by plpau** [JavaCafe01/PdfViewer#98]
### Issue Summary

Since version 3.5 (which I installed from F-Droid), this app opens the file browser in an unexpected manner. I have seen this happen in the following two scenarios:

1. on rotation of the device, i.e. switching between portrait and landscape mode;
2. upon attempting to open a PDF file from the File Manager installed on my phone.

Moreover, in scenario 1, if I open the same file again, and then go back with the intention to exit from the app, it brings me back to the same file, as if it had been opened twice and stacked on itself.

Version 3.4 works as intended, without this issue.

### Steps to Reproduce the Problem

Scenario 1:
1. Make sure your device is set to switch between portrait and landscape mode when rotating it;
2. Open any PDF file in the file browser embedded in this app;
3. While the PDF is showing, rotate your device;
Expected result: the PDF file is still shown in the alternate view (portrait or landscape, corresponding to how you're holding your device).
Obtained result: the app shows the file browser.

Scenario 2:
1. Start a file manager app in your device;
2. Select a PDF file; if more PDF viewers are installed and you're prompted to select an app to open the PDF file, choose this app.
Expected result: the PDF file is shown immediately, without going through the file browser.
Obtained result: the app shows the file browser.

### Specifications

  - App Version: 3.5
  - Android Version: 8.1.0

Please feel free to ask if any more details are needed.

**Comment by Fs00** [comment]
Hello @plpau!
The bug in scenario 1 has been fixed in #92.
Scenario 2 seems strange, using version 3.5 I couldn't reproduce it neither with Android built-in File manager nor with FX. If it didn't happen on 3.4, #92 might already have been fixed it.

> Moreover, in scenario 1, if I open the same file again, and then go back with the intention to exit from the app, it brings me back to the same file, as if it had been opened twice and stacked on itself.

This is a side-effect of the introduction of multi-document mode in version 3.5. It happens only in the specific edge case you mentioned (open the app _from launcher_ -> select a file -> re-open the same file), but I couldn't find a way to prevent it from happening (and I don't think there's an easy way to).

**Comment by plpau** [comment]
> Hello @plpau!
> The bug in scenario 1 has been fixed in #92.
> Scenario 2 seems strange, using version 3.5 I couldn't reproduce it neither with Android built-in File manager nor with FX. If it didn't happen on 3.4, #92 might already have been fixed it.
> 
> > Moreover, in scenario 1, if I open the same file again, and then go back with the intention to exit from the app, it brings me back to the same file, as if it had been opened twice and stacked on itself.
> 
> This is a side-effect of the introduction of multi-document mode in version 3.5. It happens only in the specific edge case you mentioned (open the app _from launcher_ -> select a file -> re-open the same file), but I couldn't find a way to prevent it from happening (and I don't think there's an easy way to).

Thanks for your reply.

Scenario 2 may be specific to certain file managers. I have seen it on LG phones with their built-in file manager; I suppose LG has shipped a custom file manager, different from the standard Android app, and it happens to have some quirks in how it manages intents. Since you mention that Scenario 1 is fixed in the development release, it makes sense to test the next version and see if Scenario 2 was also fixed as a side effect. Hopefully it will be so. I look forward to the next release, and will report on this.

That side-effect of loading the same document twice would also be by far less noticeable in the next release, as without the issue with device rotation, most users won't be loading the same document again in the first place.

Best regards, and keep up the good work.

**Comment by Fs00** [comment]
Update on the situation.

PR #99 will fix the subtle bug introduced by multi-document mode by avoiding to reopen the same document in a new activity.
Take note that it will be able to detect if you are opening the same document **only** if it's being opened from the same app/file picker.

After thinking more about scenario 2, I believe it could be caused by the following check that I have added in #88:
https://github.com/JavaCafe01/PdfViewer/blob/a2bb9e53efff8e4af94c6f9572a24799594ecc8e/app/src/main/java/com/gsnathan/pdfviewer/MainActivity.java#L154-L158

You should check in logcat if you see the warning line above ("No read permission for URI ...") after reproducing the issue.
In any case, I would ask you to answer the following questions:
- which Android version are you on?
- following the same exact steps, in version 3.4 were you able to read the file correctly or did you see an empty screen after opening the file?
- does it work as expected in version 3.5 if you grant storage permission to the app?

Thank you!

**Comment by Fs00** [comment]
Hello @plpau, any news after the 3.6 release? Is the bug in scenario 2 still present?

**Comment by plpau** [comment]
Hello,

sorry for the delay in updating. The behaviour of version 3.6 seems to be the following, at least according to a few tests.

If I open PDF Viewer Plus 3.6 and select a file from its own file browser, the file opens and I can switch between portrait and landscape mode without issue.

However, if I choose to open a file with PDF Viewer Plus from the LG file manager, not only am I sent to the file browser within PDF Viewer Plus (which doesn't always match the directory I was browsing - I suppose it's the last directory I viewed within PDF Viewer Plus), but once I select the file from there, switching between portrait and landscape orientation still brings me back to the app's file browser.

In answer to your query, even with version 3.6, I have lines in logcat that look like this:

03-06 13:16:48.444  8038  8038 W n       : No read permission for URI content://media/external/file/37735

which should correspond to when I open a file from the LG file manager. It seems strange, seeing as I have enabled the storage permission in the app settings. Besides, shouldn't it be unable to open the file at all if those permissions were the cause? The URI doesn't mention the pdf file explicitly, either. I don't know if that is expected.

I have tried opening a file from "Simple File Manager" from F-Droid, but I have the same issue. However, since you mentioned FX File Explorer, I have now installed that file manager from Play Store, and by using that one, the bug doesn't seem to manifest itself. Files opened from FX File Explorer are opened directly, and switching between portrait and landscape works fine.

I can try further steps to isolate the problem if you'd like. If everything fails, it might as well be a bug in something shipped by LG, though.

**Comment by Fs00** [comment]
Thanks for your further analysis! It confirmed my doubts.
The bug will be fixed in the next version.

Btw, long story short, the message "No read permission for URI" was a false negative caused by an unreliable permission check made by the app.

**Comment by JavaCafe01** [comment]
Fixed in #111
